development:
  adapter: postgresql
  database: sample_app_dev
  username: bnar
  password: secret
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: sample_app_test
  username: bnar
  password: secret
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: sample_app_prod
  username: bnar
  password: secret
  pool: 5
  timeout: 5000
  host: localhost